[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 5

[rpc_endpoints]
bsc = "${RPC_BSC}"
local = "${RPC_LOCAL}"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config